--- # webserver
server:
  port: 8080
  context-path: /book

--- # logging
logging:
  level:
#    org.springframework.web.servlet.mvc: debug
#    org.mybatis: debug

--- # datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false
    username: root
    password: admin123
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 1
    maximum-pool-size: 10
    connection-timeout: 5000

--- # template
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  #开启dev环境配置
  profiles:
    active: dev

